release: generate new bundle

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -32,5 +32,11 @@ jobs:
             echo "Failed to return Run ID"
             exit 1
           fi
+      - name: Evaluate that the Run URL output has been set
+        run: |
+          if [ "${{ steps.return_dispatch.outputs.run_url }}" == "" ]; then
+            echo "Failed to return Run ID"
+            exit 1
+          fi
       - name: Output fetched Run ID
         run: echo ${{ steps.return_dispatch.outputs.run_id }}
