Ensure action fails if not run id is returned for testing.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -28,4 +28,9 @@ jobs:
           workflow_inputs: "{\"cake\":\"delicious\"}"
           workflow_timeout_seconds: 30
       - name: Output fetched Run ID
-        run: echo ${{ steps.return_dispatch.outputs.run_id}}
+        run: |
+            if ["${{ steps.return_dispatch.outputs.run_id }}" == ""]; then
+              echo "Failed to return Run ID"
+              exit 1
+            fi
+        run: echo ${{ steps.return_dispatch.outputs.run_id }}
